name: cemantix_solver

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.9
  - jupyterlab=3.4

  ## Development tools
  - black=22.3
  - flake8=4.0
  - isort=5.10

  ## Data engineering
  - tqdm=4.64
  - pandas=1.4

  ## Machine Learning
  - gensim=4.2

  ## I/O
  - requests=2.27
  - ipywidgets=7.7
