name: cemantix_solver

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.8
  - jupyterlab

  ## Development tools
  - black
  - flake8
  - isort

  ## Data engineering
  - tqdm
  - pandas

  ## Machine Learning
  - gensim

  ## I/O
  - requests
  - ipywidgets
  
  - markupsafe<2.1

  ## pip
  - pip
  - pip:
    - nbinteract
