name: cemantix_solver

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.8
  - jupyterlab

  ## Development tools
  - black
  - flake8
  - isort

  ## Data engineering
  - tqdm=4
  - pandas=1

  ## Machine Learning
  - gensim=4

  ## I/O
  - requests=2
  - ipywidgets=7
  - voila
